In [1]:
import pandas as pd
import numpy as np

In [2]:
Data=pd.read_csv("D:/stat-road-ac-2013-2016 Sql.csv")

In [3]:
Data

,SI. No.,States/UTs,State/UT-Wise Total Number of Road Accidents during - 2013,State/UT-Wise Total Number of Road Accidents during - 2014,State/UT-Wise Total Number of Road Accidents during - 2015,State/UT-Wise Total Number of Road Accidents during - 2016,Share of States/UTs in Total Number of Road Accidents - 2013,Share of States/UTs in Total Number of Road Accidents - 2014,Share of States/UTs in Total Number of Road Accidents - 2015,Share of States/UTs in Total Number of Road Accidents - 2016,...,"Total Number of Road Accidents per 10,000 Vehicles - 2013","Total Number of Road Accidents per 10,000 Vehicles - 2014","Total Number of Road Accidents per 10,000 Vehicles - 2015","Total Number of Road Accidents per 10,000 Km of Roads - 2013","Total Number of Road Accidents per 10,000 Km of Roads - 2014","Total Number of Road Accidents per 10,000 Km of Roads - 2015",State/UT-Wise Total Number of Road Accidents during - 2013/14/15/16,Aggregate Average Share of States/UTs in Total Number of Road Accidents - 2013/14/15/16,"Average Total No of Road Accidents per 10,000 Vehicles - 2013/14/15",Avreage of Total No of Accidents Per lakh Population - 2013/14/15/16
0,1,Andhra Pradesh,43482.0,24440,24258,24888,8.9,5.0,4.8,5.2,...,34.3,34.9,30.8,1661.8,1372.3,1355.0,117068,5.98,33.3,33.6
1,2,Arunachal Pradesh,308.0,205,284,249,0.1,0.0,0.1,0.1,...,20.4,13.6,18.8,109.6,83.8,112.0,1046,0.08,17.6,20.3
2,3,Assam,7211.0,7144,6959,7435,1.5,1.5,1.4,1.5,...,38.4,32.2,27.7,250.3,227.8,213.1,28749,1.48,32.8,22.5
3,4,Bihar,10200.0,9556,9555,8222,2.1,2.0,1.9,1.7,...,28.2,23.0,20.0,517.1,455.6,463.8,37533,1.93,23.7,9.2
4,5,Chhattisgarh,13657.0,13821,14446,13580,2.8,2.8,2.9,2.8,...,39.7,35.7,33.5,1530.4,1461.3,1481.1,55504,2.83,36.3,54.7
5,6,Goa,4294.0,4229,4338,4304,0.9,0.9,0.9,0.9,...,45.8,41.9,40.0,3702.2,3187.6,2966.4,17165,0.90,42.6,222.6
6,7,Gujarat,25391.0,23712,23183,21859,5.2,4.8,4.6,4.5,...,16.1,13.9,12.4,1532.9,1324.2,1271.8,94145,4.78,14.1,38.2
7,8,Haryana,10482.0,10676,11174,11234,2.2,2.2,2.2,2.3,...,15.9,14.7,14.1,2467.7,2501.1,2414.1,43566,2.23,14.9,40.5
8,9,Himachal Pradesh,2981.0,3058,3010,3168,0.6,0.6,0.6,0.7,...,34.0,31.4,27.9,560.1,562.3,541.4,12217,0.63,31.1,43.6
9,10,Jammu & Kashmir,6457.0,5861,5836,5501,1.3,1.2,1.2,1.1,...,63.3,51.7,46.9,1447.9,1498.7,1492.7,23655,1.20,54.0,48.5
10,11,Jharkhand,5569.0,5201,5162,4932,1.1,1.1,1.0,1.0,...,16.6,30.3,25.0,1502.5,1260.6,1208.8,20864,1.05,24.0,15.8
11,12,Karnataka,44020.0,43713,44011,44403,9.0,8.9,8.8,9.2,...,36.5,32.8,29.8,1441.2,1395.8,1367.6,176147,8.98,33.0,71.6
12,13,Kerala,35215.0,36282,39014,39420,7.2,7.4,7.8,8.2,...,44.8,41.3,40.4,1903.2,1875.4,2002.2,149931,7.65,42.2,106.0
13,14,Madhya Pradesh,51810.0,53472,54947,53972,10.7,10.9,11.0,11.2,...,59.1,55.0,49.3,2264.3,1909.7,1901.7,214201,10.95,54.5,70.3
14,15,Maharashtra,63019.0,61627,63805,39878,13.0,12.6,12.7,8.3,...,29.3,26.3,25.0,1068.8,1012.5,1049.2,228329,11.65,26.9,48.5
15,16,Manipur,671.0,743,671,538,0.1,0.2,0.1,0.1,...,22.7,18.8,21.8,322.0,343.0,276.7,2623,0.13,21.1,25.8
16,17,Meghalaya,525.0,542,606,620,0.1,0.1,0.1,0.1,...,23.9,21.8,22.7,426.2,408.7,453.2,2293,0.10,22.8,21.0
17,18,Mizoram,114.0,132,70,83,0.0,0.0,0.0,0.0,...,9.4,9.6,4.6,104.2,134.7,71.2,399,0.00,7.9,9.6
18,19,Nagaland,71.0,305,54,75,0.0,0.1,0.0,0.0,...,2.3,9.6,1.6,18.5,83.3,14.5,505,0.03,4.5,5.4
19,20,Odisha,9680.0,9648,10542,10532,2.0,2.0,2.1,2.2,...,23.0,20.5,20.2,348.6,340.7,371.6,40402,2.08,21.2,24.1
20,21,Punjab,6323.0,6391,6702,6952,1.3,1.3,1.3,1.4,...,9.0,10.2,10.7,642.3,613.6,636.1,26368,1.33,10.0,23.0
21,22,Rajasthan,23592.0,24628,24072,23066,4.8,5.0,4.8,4.8,...,23.4,22.1,19.4,1043.3,1020.9,970.0,95358,4.85,21.6,33.4
22,23,Sikkim,244.0,203,219,210,0.1,0.0,0.0,0.0,...,67.3,51.3,50.7,371.4,311.1,294.0,876,0.03,56.4,34.5
23,24,Tamil Nadu,66238.0,67250,69059,71431,13.6,13.7,13.8,14.9,...,34.4,32.2,30.7,2783.1,2645.5,2644.9,273978,14.00,32.4,99.5
24,25,Telangana,NaN,20078,21252,22811,0.0,4.1,4.2,4.7,...,NaN,28.4,27.1,NaN,2177.3,2119.9,64141,3.25,27.8,NaN
25,26,Tripura,818.0,716,647,557,0.2,0.1,0.1,0.1,...,33.4,28.0,22.9,263.7,171.1,173.1,2738,0.13,28.1,18.2
26,27,Uttarakhand,1297.0,1410,1523,1591,0.3,0.3,0.3,0.3,...,8.9,8.6,8.3,220.9,233.3,242.0,5821,0.30,8.6,14.0
27,28,Uttar Pradesh,30615.0,31034,32385,35612,6.3,6.3,6.5,7.4,...,18.0,16.2,15.0,702.2,781.3,779.6,129646,6.63,16.4,15.2
28,29,West Bengal,12414.0,12875,13208,13580,2.6,2.6,2.6,2.8,...,27.6,19.1,17.8,400.8,410.4,446.2,52077,2.65,21.5,14.1
29,30,Andaman & Nicobar Islands,200.0,218,258,238,0.0,0.0,0.1,0.0,...,23.4,23.3,25.2,1440.9,1654.0,1908.3,914,0.03,24.0,42.5
30,31,Chandigarh,410.0,369,416,428,0.1,0.1,0.1,0.1,...,3.7,5.9,6.1,2057.2,1281.6,1417.4,1623,0.10,5.2,24.1
31,32,Dadra & Nagar Haveli,91.0,87,69,70,0.0,0.0,0.0,0.0,...,9.7,8.5,6.2,1123.5,1034.5,797.7,317,0.00,8.1,19.6
32,33,Daman & Diu,59.0,39,70,71,0.0,0.0,0.0,0.0,...,6.4,4.1,7.0,3105.3,769.2,1341.0,239,0.00,5.8,19.1
33,34,Delhi,7566.0,8623,8085,7375,1.6,1.8,1.6,1.5,...,9.7,10.4,9.1,2364.7,2695.0,2521.3,31649,1.63,9.7,38.8
34,35,Lakshadweep,1.0,1,3,1,0.0,0.0,0.0,0.0,...,0.9,0.8,2.1,48.3,48.1,140.2,6,0.00,1.3,1.9
35,36,Puducherry,1451.0,1111,1530,1766,0.3,0.2,0.3,0.4,...,20.7,14.8,19.1,5020.5,3678.9,4980.2,5858,0.30,18.2,91.6
36,Total,Total,486476.0,489400,501423,480652,100.0,100.0,100.0,100.0,...,27.0,26.3,22.9,1129.8,1113.7,1051.3,1957951,100.00,25.4,39.2

In [9]:
Data['Avreage of Total No of Accidents Per lakh Population - 2013/14/15/16']= Data['Avreage of Total No of Accidents Per lakh Population - 2013/14/15/16'].fillna(Data['Avreage of Total No of Accidents Per lakh Population - 2013/14/15/16'].mean())

In [5]:
Data.isnull().sum()

SI. No.                                                                                     0
States/UTs                                                                                  0
State/UT-Wise Total Number of Road Accidents during - 2013                                  1
State/UT-Wise Total Number of Road Accidents during - 2014                                  0
State/UT-Wise Total Number of Road Accidents during - 2015                                  0
State/UT-Wise Total Number of Road Accidents during - 2016                                  0
Share of States/UTs in Total Number of Road Accidents - 2013                                0
Share of States/UTs in Total Number of Road Accidents - 2014                                0
Share of States/UTs in Total Number of Road Accidents - 2015                                0
Share of States/UTs in Total Number of Road Accidents - 2016                                0
Total Number of Accidents Per Lakh Population - 2013                                        1
Total Number of Accidents Per Lakh Population - 2014                                        1
Total Number of Accidents Per Lakh Population - 2015                                        1
Total Number of Accidents Per Lakh Population - 2016                                        1
Total Number of Road Accidents per 10,000 Vehicles - 2013                                   1
Total Number of Road Accidents per 10,000 Vehicles - 2014                                   0
Total Number of Road Accidents per 10,000 Vehicles - 2015                                   0
Total Number of Road Accidents per 10,000 Km of Roads - 2013                                1
Total Number of Road Accidents per 10,000 Km of Roads - 2014                                0
Total Number of Road Accidents per 10,000 Km of Roads - 2015                                0
State/UT-Wise Total Number of Road Accidents during - 2013/14/15/16                         0
 Aggregate Average Share of States/UTs in Total Number of Road Accidents - 2013/14/15/16    0
Average Total No of Road Accidents per 10,000 Vehicles - 2013/14/15                         0
Avreage of Total No of Accidents Per lakh Population - 2013/14/15/16                        1
dtype: int64

In [10]:
Data.isnull().sum()

SI. No.                                                                                     0
States/UTs                                                                                  0
State/UT-Wise Total Number of Road Accidents during - 2013                                  1
State/UT-Wise Total Number of Road Accidents during - 2014                                  0
State/UT-Wise Total Number of Road Accidents during - 2015                                  0
State/UT-Wise Total Number of Road Accidents during - 2016                                  0
Share of States/UTs in Total Number of Road Accidents - 2013                                0
Share of States/UTs in Total Number of Road Accidents - 2014                                0
Share of States/UTs in Total Number of Road Accidents - 2015                                0
Share of States/UTs in Total Number of Road Accidents - 2016                                0
Total Number of Accidents Per Lakh Population - 2013                                        1
Total Number of Accidents Per Lakh Population - 2014                                        1
Total Number of Accidents Per Lakh Population - 2015                                        1
Total Number of Accidents Per Lakh Population - 2016                                        1
Total Number of Road Accidents per 10,000 Vehicles - 2013                                   1
Total Number of Road Accidents per 10,000 Vehicles - 2014                                   0
Total Number of Road Accidents per 10,000 Vehicles - 2015                                   0
Total Number of Road Accidents per 10,000 Km of Roads - 2013                                1
Total Number of Road Accidents per 10,000 Km of Roads - 2014                                0
Total Number of Road Accidents per 10,000 Km of Roads - 2015                                0
State/UT-Wise Total Number of Road Accidents during - 2013/14/15/16                         0
 Aggregate Average Share of States/UTs in Total Number of Road Accidents - 2013/14/15/16    0
Average Total No of Road Accidents per 10,000 Vehicles - 2013/14/15                         0
Avreage of Total No of Accidents Per lakh Population - 2013/14/15/16                        0
dtype: int64

In [11]:
Data.head()

,SI. No.,States/UTs,State/UT-Wise Total Number of Road Accidents during - 2013,State/UT-Wise Total Number of Road Accidents during - 2014,State/UT-Wise Total Number of Road Accidents during - 2015,State/UT-Wise Total Number of Road Accidents during - 2016,Share of States/UTs in Total Number of Road Accidents - 2013,Share of States/UTs in Total Number of Road Accidents - 2014,Share of States/UTs in Total Number of Road Accidents - 2015,Share of States/UTs in Total Number of Road Accidents - 2016,...,"Total Number of Road Accidents per 10,000 Vehicles - 2013","Total Number of Road Accidents per 10,000 Vehicles - 2014","Total Number of Road Accidents per 10,000 Vehicles - 2015","Total Number of Road Accidents per 10,000 Km of Roads - 2013","Total Number of Road Accidents per 10,000 Km of Roads - 2014","Total Number of Road Accidents per 10,000 Km of Roads - 2015",State/UT-Wise Total Number of Road Accidents during - 2013/14/15/16,Aggregate Average Share of States/UTs in Total Number of Road Accidents - 2013/14/15/16,"Average Total No of Road Accidents per 10,000 Vehicles - 2013/14/15",Avreage of Total No of Accidents Per lakh Population - 2013/14/15/16
0,1,Andhra Pradesh,43482.0,24440,24258,24888,8.9,5.0,4.8,5.2,...,34.3,34.9,30.8,1661.8,1372.3,1355.0,117068,5.98,33.3,33.6
1,2,Arunachal Pradesh,308.0,205,284,249,0.1,0.0,0.1,0.1,...,20.4,13.6,18.8,109.6,83.8,112.0,1046,0.08,17.6,20.3
2,3,Assam,7211.0,7144,6959,7435,1.5,1.5,1.4,1.5,...,38.4,32.2,27.7,250.3,227.8,213.1,28749,1.48,32.8,22.5
3,4,Bihar,10200.0,9556,9555,8222,2.1,2.0,1.9,1.7,...,28.2,23.0,20.0,517.1,455.6,463.8,37533,1.93,23.7,9.2
4,5,Chhattisgarh,13657.0,13821,14446,13580,2.8,2.8,2.9,2.8,...,39.7,35.7,33.5,1530.4,1461.3,1481.1,55504,2.83,36.3,54.7

In [12]:
Data['Avreage of Total No of Accidents Per lakh Population - 2013/14/15/16'].value_counts().nlargest(5)

48.5    2
24.1    2
33.4    1
34.5    1
99.5    1
Name: Avreage of Total No of Accidents Per lakh Population - 2013/14/15/16, dtype: int64

In [13]:
Data = Data.sort_values(by=["Avreage of Total No of Accidents Per lakh Population - 2013/14/15/16"], ascending=False)

In [14]:
Data.head()

,SI. No.,States/UTs,State/UT-Wise Total Number of Road Accidents during - 2013,State/UT-Wise Total Number of Road Accidents during - 2014,State/UT-Wise Total Number of Road Accidents during - 2015,State/UT-Wise Total Number of Road Accidents during - 2016,Share of States/UTs in Total Number of Road Accidents - 2013,Share of States/UTs in Total Number of Road Accidents - 2014,Share of States/UTs in Total Number of Road Accidents - 2015,Share of States/UTs in Total Number of Road Accidents - 2016,...,"Total Number of Road Accidents per 10,000 Vehicles - 2013","Total Number of Road Accidents per 10,000 Vehicles - 2014","Total Number of Road Accidents per 10,000 Vehicles - 2015","Total Number of Road Accidents per 10,000 Km of Roads - 2013","Total Number of Road Accidents per 10,000 Km of Roads - 2014","Total Number of Road Accidents per 10,000 Km of Roads - 2015",State/UT-Wise Total Number of Road Accidents during - 2013/14/15/16,Aggregate Average Share of States/UTs in Total Number of Road Accidents - 2013/14/15/16,"Average Total No of Road Accidents per 10,000 Vehicles - 2013/14/15",Avreage of Total No of Accidents Per lakh Population - 2013/14/15/16
5,6,Goa,4294.0,4229,4338,4304,0.9,0.9,0.9,0.9,...,45.8,41.9,40.0,3702.2,3187.6,2966.4,17165,0.90,42.6,222.600000
12,13,Kerala,35215.0,36282,39014,39420,7.2,7.4,7.8,8.2,...,44.8,41.3,40.4,1903.2,1875.4,2002.2,149931,7.65,42.2,106.000000
23,24,Tamil Nadu,66238.0,67250,69059,71431,13.6,13.7,13.8,14.9,...,34.4,32.2,30.7,2783.1,2645.5,2644.9,273978,14.00,32.4,99.500000
35,36,Puducherry,1451.0,1111,1530,1766,0.3,0.2,0.3,0.4,...,20.7,14.8,19.1,5020.5,3678.9,4980.2,5858,0.30,18.2,91.600000
11,12,Karnataka,44020.0,43713,44011,44403,9.0,8.9,8.8,9.2,...,36.5,32.8,29.8,1441.2,1395.8,1367.6,176147,8.98,33.0,71.600000
13,14,Madhya Pradesh,51810.0,53472,54947,53972,10.7,10.9,11.0,11.2,...,59.1,55.0,49.3,2264.3,1909.7,1901.7,214201,10.95,54.5,70.300000
4,5,Chhattisgarh,13657.0,13821,14446,13580,2.8,2.8,2.9,2.8,...,39.7,35.7,33.5,1530.4,1461.3,1481.1,55504,2.83,36.3,54.700000
9,10,Jammu & Kashmir,6457.0,5861,5836,5501,1.3,1.2,1.2,1.1,...,63.3,51.7,46.9,1447.9,1498.7,1492.7,23655,1.20,54.0,48.500000
14,15,Maharashtra,63019.0,61627,63805,39878,13.0,12.6,12.7,8.3,...,29.3,26.3,25.0,1068.8,1012.5,1049.2,228329,11.65,26.9,48.500000
8,9,Himachal Pradesh,2981.0,3058,3010,3168,0.6,0.6,0.6,0.7,...,34.0,31.4,27.9,560.1,562.3,541.4,12217,0.63,31.1,43.600000
29,30,Andaman & Nicobar Islands,200.0,218,258,238,0.0,0.0,0.1,0.0,...,23.4,23.3,25.2,1440.9,1654.0,1908.3,914,0.03,24.0,42.500000
24,25,Telangana,NaN,20078,21252,22811,0.0,4.1,4.2,4.7,...,NaN,28.4,27.1,NaN,2177.3,2119.9,64141,3.25,27.8,40.569444
7,8,Haryana,10482.0,10676,11174,11234,2.2,2.2,2.2,2.3,...,15.9,14.7,14.1,2467.7,2501.1,2414.1,43566,2.23,14.9,40.500000
36,Total,Total,486476.0,489400,501423,480652,100.0,100.0,100.0,100.0,...,27.0,26.3,22.9,1129.8,1113.7,1051.3,1957951,100.00,25.4,39.200000
33,34,Delhi,7566.0,8623,8085,7375,1.6,1.8,1.6,1.5,...,9.7,10.4,9.1,2364.7,2695.0,2521.3,31649,1.63,9.7,38.800000
6,7,Gujarat,25391.0,23712,23183,21859,5.2,4.8,4.6,4.5,...,16.1,13.9,12.4,1532.9,1324.2,1271.8,94145,4.78,14.1,38.200000
22,23,Sikkim,244.0,203,219,210,0.1,0.0,0.0,0.0,...,67.3,51.3,50.7,371.4,311.1,294.0,876,0.03,56.4,34.500000
0,1,Andhra Pradesh,43482.0,24440,24258,24888,8.9,5.0,4.8,5.2,...,34.3,34.9,30.8,1661.8,1372.3,1355.0,117068,5.98,33.3,33.600000
21,22,Rajasthan,23592.0,24628,24072,23066,4.8,5.0,4.8,4.8,...,23.4,22.1,19.4,1043.3,1020.9,970.0,95358,4.85,21.6,33.400000
15,16,Manipur,671.0,743,671,538,0.1,0.2,0.1,0.1,...,22.7,18.8,21.8,322.0,343.0,276.7,2623,0.13,21.1,25.800000
30,31,Chandigarh,410.0,369,416,428,0.1,0.1,0.1,0.1,...,3.7,5.9,6.1,2057.2,1281.6,1417.4,1623,0.10,5.2,24.100000
19,20,Odisha,9680.0,9648,10542,10532,2.0,2.0,2.1,2.2,...,23.0,20.5,20.2,348.6,340.7,371.6,40402,2.08,21.2,24.100000
20,21,Punjab,6323.0,6391,6702,6952,1.3,1.3,1.3,1.4,...,9.0,10.2,10.7,642.3,613.6,636.1,26368,1.33,10.0,23.000000
2,3,Assam,7211.0,7144,6959,7435,1.5,1.5,1.4,1.5,...,38.4,32.2,27.7,250.3,227.8,213.1,28749,1.48,32.8,22.500000
16,17,Meghalaya,525.0,542,606,620,0.1,0.1,0.1,0.1,...,23.9,21.8,22.7,426.2,408.7,453.2,2293,0.10,22.8,21.000000
1,2,Arunachal Pradesh,308.0,205,284,249,0.1,0.0,0.1,0.1,...,20.4,13.6,18.8,109.6,83.8,112.0,1046,0.08,17.6,20.300000
31,32,Dadra & Nagar Haveli,91.0,87,69,70,0.0,0.0,0.0,0.0,...,9.7,8.5,6.2,1123.5,1034.5,797.7,317,0.00,8.1,19.600000
32,33,Daman & Diu,59.0,39,70,71,0.0,0.0,0.0,0.0,...,6.4,4.1,7.0,3105.3,769.2,1341.0,239,0.00,5.8,19.100000
25,26,Tripura,818.0,716,647,557,0.2,0.1,0.1,0.1,...,33.4,28.0,22.9,263.7,171.1,173.1,2738,0.13,28.1,18.200000
10,11,Jharkhand,5569.0,5201,5162,4932,1.1,1.1,1.0,1.0,...,16.6,30.3,25.0,1502.5,1260.6,1208.8,20864,1.05,24.0,15.800000
27,28,Uttar Pradesh,30615.0,31034,32385,35612,6.3,6.3,6.5,7.4,...,18.0,16.2,15.0,702.2,781.3,779.6,129646,6.63,16.4,15.200000
28,29,West Bengal,12414.0,12875,13208,13580,2.6,2.6,2.6,2.8,...,27.6,19.1,17.8,400.8,410.4,446.2,52077,2.65,21.5,14.100000
26,27,Uttarakhand,1297.0,1410,1523,1591,0.3,0.3,0.3,0.3,...,8.9,8.6,8.3,220.9,233.3,242.0,5821,0.30,8.6,14.000000
17,18,Mizoram,114.0,132,70,83,0.0,0.0,0.0,0.0,...,9.4,9.6,4.6,104.2,134.7,71.2,399,0.00,7.9,9.600000
3,4,Bihar,10200.0,9556,9555,8222,2.1,2.0,1.9,1.7,...,28.2,23.0,20.0,517.1,455.6,463.8,37533,1.93,23.7,9.200000
18,19,Nagaland,71.0,305,54,75,0.0,0.1,0.0,0.0,...,2.3,9.6,1.6,18.5,83.3,14.5,505,0.03,4.5,5.400000
34,35,Lakshadweep,1.0,1,3,1,0.0,0.0,0.0,0.0,...,0.9,0.8,2.1,48.3,48.1,140.2,6,0.00,1.3,1.900000

In [16]:
Star_Road=Data[["SI. No.","States/UTs","State/UT-Wise Total Number of Road Accidents during - 2013/14/15/16","Average Total No of Road Accidents per 10,000 Vehicles - 2013/14/15","Avreage of Total No of Accidents Per lakh Population - 2013/14/15/16"]]

In [18]:
Total_NO_Of_Accident_StateWise=Star_Road.sort_values(by=["State/UT-Wise Total Number of Road Accidents during - 2013/14/15/16"],ascending=False)

In [19]:
Total_NO_Of_Accident_StateWise

,SI. No.,States/UTs,State/UT-Wise Total Number of Road Accidents during - 2013/14/15/16,"Average Total No of Road Accidents per 10,000 Vehicles - 2013/14/15",Avreage of Total No of Accidents Per lakh Population - 2013/14/15/16
36,Total,Total,1957951,25.4,39.200000
23,24,Tamil Nadu,273978,32.4,99.500000
14,15,Maharashtra,228329,26.9,48.500000
13,14,Madhya Pradesh,214201,54.5,70.300000
11,12,Karnataka,176147,33.0,71.600000
12,13,Kerala,149931,42.2,106.000000
27,28,Uttar Pradesh,129646,16.4,15.200000
0,1,Andhra Pradesh,117068,33.3,33.600000
21,22,Rajasthan,95358,21.6,33.400000
6,7,Gujarat,94145,14.1,38.200000
24,25,Telangana,64141,27.8,40.569444
4,5,Chhattisgarh,55504,36.3,54.700000
28,29,West Bengal,52077,21.5,14.100000
7,8,Haryana,43566,14.9,40.500000
19,20,Odisha,40402,21.2,24.100000
3,4,Bihar,37533,23.7,9.200000
33,34,Delhi,31649,9.7,38.800000
2,3,Assam,28749,32.8,22.500000
20,21,Punjab,26368,10.0,23.000000
9,10,Jammu & Kashmir,23655,54.0,48.500000
10,11,Jharkhand,20864,24.0,15.800000
5,6,Goa,17165,42.6,222.600000
8,9,Himachal Pradesh,12217,31.1,43.600000
35,36,Puducherry,5858,18.2,91.600000
26,27,Uttarakhand,5821,8.6,14.000000
25,26,Tripura,2738,28.1,18.200000
15,16,Manipur,2623,21.1,25.800000
16,17,Meghalaya,2293,22.8,21.000000
30,31,Chandigarh,1623,5.2,24.100000
1,2,Arunachal Pradesh,1046,17.6,20.300000
29,30,Andaman & Nicobar Islands,914,24.0,42.500000
22,23,Sikkim,876,56.4,34.500000
18,19,Nagaland,505,4.5,5.400000
17,18,Mizoram,399,7.9,9.600000
31,32,Dadra & Nagar Haveli,317,8.1,19.600000
32,33,Daman & Diu,239,5.8,19.100000
34,35,Lakshadweep,6,1.3,1.900000

In [20]:
Total_NO_Of_Accident_StateWise.tail()#Nagaland has the lowest Accident count in the whole country

,SI. No.,States/UTs,State/UT-Wise Total Number of Road Accidents during - 2013/14/15/16,"Average Total No of Road Accidents per 10,000 Vehicles - 2013/14/15",Avreage of Total No of Accidents Per lakh Population - 2013/14/15/16
18,19,Nagaland,505,4.5,5.4
17,18,Mizoram,399,7.9,9.6
31,32,Dadra & Nagar Haveli,317,8.1,19.6
32,33,Daman & Diu,239,5.8,19.1
34,35,Lakshadweep,6,1.3,1.9

In [21]:
Total_NO_Of_Accident_StateWise.head()
# Tamil Nadu has the highest Accidents in the country 
#Maharashtra is the second topper in this list.

,SI. No.,States/UTs,State/UT-Wise Total Number of Road Accidents during - 2013/14/15/16,"Average Total No of Road Accidents per 10,000 Vehicles - 2013/14/15",Avreage of Total No of Accidents Per lakh Population - 2013/14/15/16
36,Total,Total,1957951,25.4,39.2
23,24,Tamil Nadu,273978,32.4,99.5
14,15,Maharashtra,228329,26.9,48.5
13,14,Madhya Pradesh,214201,54.5,70.3
11,12,Karnataka,176147,33.0,71.6

In [22]:
Star_Road

,SI. No.,States/UTs,State/UT-Wise Total Number of Road Accidents during - 2013/14/15/16,"Average Total No of Road Accidents per 10,000 Vehicles - 2013/14/15",Avreage of Total No of Accidents Per lakh Population - 2013/14/15/16
5,6,Goa,17165,42.6,222.600000
12,13,Kerala,149931,42.2,106.000000
23,24,Tamil Nadu,273978,32.4,99.500000
35,36,Puducherry,5858,18.2,91.600000
11,12,Karnataka,176147,33.0,71.600000
13,14,Madhya Pradesh,214201,54.5,70.300000
4,5,Chhattisgarh,55504,36.3,54.700000
9,10,Jammu & Kashmir,23655,54.0,48.500000
14,15,Maharashtra,228329,26.9,48.500000
8,9,Himachal Pradesh,12217,31.1,43.600000
29,30,Andaman & Nicobar Islands,914,24.0,42.500000
24,25,Telangana,64141,27.8,40.569444
7,8,Haryana,43566,14.9,40.500000
36,Total,Total,1957951,25.4,39.200000
33,34,Delhi,31649,9.7,38.800000
6,7,Gujarat,94145,14.1,38.200000
22,23,Sikkim,876,56.4,34.500000
0,1,Andhra Pradesh,117068,33.3,33.600000
21,22,Rajasthan,95358,21.6,33.400000
15,16,Manipur,2623,21.1,25.800000
30,31,Chandigarh,1623,5.2,24.100000
19,20,Odisha,40402,21.2,24.100000
20,21,Punjab,26368,10.0,23.000000
2,3,Assam,28749,32.8,22.500000
16,17,Meghalaya,2293,22.8,21.000000
1,2,Arunachal Pradesh,1046,17.6,20.300000
31,32,Dadra & Nagar Haveli,317,8.1,19.600000
32,33,Daman & Diu,239,5.8,19.100000
25,26,Tripura,2738,28.1,18.200000
10,11,Jharkhand,20864,24.0,15.800000
27,28,Uttar Pradesh,129646,16.4,15.200000
28,29,West Bengal,52077,21.5,14.100000
26,27,Uttarakhand,5821,8.6,14.000000
17,18,Mizoram,399,7.9,9.600000
3,4,Bihar,37533,23.7,9.200000
18,19,Nagaland,505,4.5,5.400000
34,35,Lakshadweep,6,1.3,1.900000

In [23]:
datatoexcel= pd.ExcelWriter('C:/Users/saurabh lembhe/Desktop/Star_Road_Analysis1.xlsx')
Star_Road.to_excel(datatoexcel)
datatoexcel.save()

PermissionError: [Errno 13] Permission denied: 'C:/Users/saurabh lembhe/Desktop/Star_Road_Analysis1.xlsx'

In [24]:
file_name = "Star_Road_Analysis1.xlsx"

In [29]:
Star_Road.to_excel("C:\Users\saurabh lembhe\Desktop\Star_Road_Analysis1.xlsx")

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (3781591969.py, line 1)

In [30]:
Star_Road.to_excel("C:/Users/saurabh lembhe/Desktop/Star_Road_Analysis1.xlsx")
#Exported Star_Road data frame into excel for data visualization